<template><div><table>
<thead>
<tr>
<th>序号</th>
<th>名称</th>
<th>链接</th>
<th>网站说明</th>
</tr>
</thead>
<tbody>
<tr>
<td>01</td>
<td><strong>Oh-la!</strong></td>
<td><a href="https://www.thomasxiao.com" target="_blank" rel="noopener noreferrer">https://www.thomasxiao.com<ExternalLinkIcon/></a></td>
<td></td>
</tr>
<tr>
<td>02</td>
<td><strong>初的小站</strong></td>
<td><a href="https://www.songonline.top/" target="_blank" rel="noopener noreferrer">https://www.songonline.top/<ExternalLinkIcon/></a></td>
<td>记录分享自己的生活</td>
</tr>
<tr>
<td>03</td>
<td><strong>danniepython</strong></td>
<td><a href="http://www.danniepython.com/" target="_blank" rel="noopener noreferrer">http://www.danniepython.com/<ExternalLinkIcon/></a></td>
<td>学员笔记网站</td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</div></template>


