<template><div><h2 id="为什么需要掌握新的库" tabindex="-1"><a class="header-anchor" href="#为什么需要掌握新的库" aria-hidden="true">#</a> 为什么需要掌握新的库</h2>
<h4 id="操作xls" tabindex="-1"><a class="header-anchor" href="#操作xls" aria-hidden="true">#</a> 操作xls</h4>
<p>xlrd 和 xlwt，以及 xlutils 足以满足对xls文件的读、写、追加功能。</p>
<p>但是办公文件的格式，不是 xls，还有 xlsx，还有我们很少见的 xlsm 等。</p>
<h4 id="操作xlsx" tabindex="-1"><a class="header-anchor" href="#操作xlsx" aria-hidden="true">#</a> 操作xlsx</h4>
<p>xlsx 是 xls 的升级版，xls 是老版本的办公软件所支持的文件格式，且劣势也比较明显，当文件数据超过 65536 行和 256 列，使用 xls 则会导致数据截断。</p>
<p><img src="@source/column/pyauto/auto_base11.assets/image-20220717162403684.png" alt="image-20220717162403684" loading="lazy"></p>
<p>xlsx 的支持则更好，同样多的数据，xlsx 格式的文件体积小，支持的操作更多，软件打开和动作执行的速度会更快。</p>
<p>本次介绍的库是 xlsxwriter 和 openpyxl，这两个库均支持操作 xlsx 文件格式。</p>
<p>掌握 xlsx 的读写操作，也是大势所趋。</p>
<h2 id="写入头部标题" tabindex="-1"><a class="header-anchor" href="#写入头部标题" aria-hidden="true">#</a> 写入头部标题</h2>
<p>首先是学习 xlsxwriter 库，安装命令：<code v-pre>pip install xlsxwriter</code>。</p>
<p>第一步先导入库，以及打开一个 xlsx 文件：</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code><span class="token keyword">import</span> xlsxwriter<span class="token punctuation">,</span> random  <span class="token comment"># 导入模块</span>

wb <span class="token operator">=</span> xlsxwriter<span class="token punctuation">.</span>Workbook<span class="token punctuation">(</span><span class="token string">'xlsxwriter插入数据.xlsx'</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>xlsx 和 xls 的操作都是一致的，单个文件，里面可以添加多个 sheet。打开文件后，需要新建第一个 sheet。</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>worksheet1 <span class="token operator">=</span> wb<span class="token punctuation">.</span>add_worksheet<span class="token punctuation">(</span><span class="token string">'代码操作记录'</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>有了 sheet，开始准备标题和数据并写入文件。首先是头部标题：</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>headings <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">'日期'</span><span class="token punctuation">,</span> <span class="token string">'数据1'</span><span class="token punctuation">,</span> <span class="token string">'数据2'</span><span class="token punctuation">]</span>
worksheet1<span class="token punctuation">.</span>write_row<span class="token punctuation">(</span><span class="token string">'A1'</span><span class="token punctuation">,</span> headings<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>标题保存在 headings 中，列表格式，然后逐个写入到 sheet 中。</p>
<p>但是这里的写入操作，不是行数、列数、数据格式的单个数据写入操作，而是直接写入一行或者一列。这里用的是写入 <code v-pre>wtier_row</code>，写入一行，从 A1 开始，然后 A2、A3，一直往后写。</p>
<h2 id="写入数据内容" tabindex="-1"><a class="header-anchor" href="#写入数据内容" aria-hidden="true">#</a> 写入数据内容</h2>
<p>接下来写入数据，首先是创造数据，结构也是列表格式，然后使用写入列的操作，将数据整行的写入。</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>data <span class="token operator">=</span> <span class="token punctuation">[</span>
    <span class="token punctuation">[</span><span class="token string">'2022-1'</span><span class="token punctuation">,</span> <span class="token string">'2022-2'</span><span class="token punctuation">,</span> <span class="token string">'2022-3'</span><span class="token punctuation">,</span> <span class="token string">'2022-4'</span><span class="token punctuation">,</span> <span class="token string">'2022-5'</span><span class="token punctuation">,</span> <span class="token string">'2022-6'</span><span class="token punctuation">,</span> <span class="token string">'2022-7'</span><span class="token punctuation">,</span> <span class="token string">'2022-8'</span><span class="token punctuation">,</span> <span class="token string">'2022-9'</span><span class="token punctuation">,</span> <span class="token string">'2022-10'</span><span class="token punctuation">,</span> <span class="token string">'2022-11'</span><span class="token punctuation">,</span>
     <span class="token string">'2022-12'</span><span class="token punctuation">,</span> <span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span>random<span class="token punctuation">.</span>randint<span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">100</span><span class="token punctuation">)</span> <span class="token keyword">for</span> i <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token number">12</span><span class="token punctuation">)</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span>random<span class="token punctuation">.</span>randint<span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">100</span><span class="token punctuation">)</span> <span class="token keyword">for</span> i <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token number">12</span><span class="token punctuation">)</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
<span class="token punctuation">]</span>
worksheet1<span class="token punctuation">.</span>write_column<span class="token punctuation">(</span><span class="token string">'A2'</span><span class="token punctuation">,</span> data<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
worksheet1<span class="token punctuation">.</span>write_column<span class="token punctuation">(</span><span class="token string">'B2'</span><span class="token punctuation">,</span> data<span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
worksheet1<span class="token punctuation">.</span>write_column<span class="token punctuation">(</span><span class="token string">'C2'</span><span class="token punctuation">,</span> data<span class="token punctuation">[</span><span class="token number">2</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>这里的数据使用了random 库随机设置，所以第一块代码中，有 random 的导入。</p>
<p>data 是列表，里面有三个列表，分别是日期和两类数据，结合头部标题，写入的数据，是三列，所以用的是 <code v-pre>write_column</code> 函数。</p>
<p>写完之后，直接关闭即可。</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>wb<span class="token punctuation">.</span>close<span class="token punctuation">(</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>用 Office 打开文件，如下图：</p>
<p><img src="@source/column/pyauto/auto_base11.assets/image-20220717173517827.png" alt="image-20220717173517827" loading="lazy"></p>
<p>数据写入完毕。</p>
<p><strong>补充：</strong></p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>data <span class="token operator">=</span> <span class="token punctuation">[</span>
    <span class="token punctuation">[</span><span class="token string">'2022-{i}'</span><span class="token punctuation">.</span><span class="token builtin">format</span><span class="token punctuation">(</span>i<span class="token operator">=</span>i<span class="token punctuation">)</span> <span class="token keyword">for</span> i <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">13</span><span class="token punctuation">)</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span>random<span class="token punctuation">.</span>randint<span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">100</span><span class="token punctuation">)</span> <span class="token keyword">for</span> i <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token number">12</span><span class="token punctuation">)</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span>random<span class="token punctuation">.</span>randint<span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">100</span><span class="token punctuation">)</span> <span class="token keyword">for</span> i <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token number">12</span><span class="token punctuation">)</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
<span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>当前完整代码：</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code><span class="token keyword">import</span> xlsxwriter
<span class="token keyword">import</span> random  <span class="token comment"># 导入模块</span>

wb <span class="token operator">=</span> xlsxwriter<span class="token punctuation">.</span>Workbook<span class="token punctuation">(</span><span class="token string">'xlsxwriter插入数据.xlsx'</span><span class="token punctuation">)</span>
worksheet1 <span class="token operator">=</span> wb<span class="token punctuation">.</span>add_worksheet<span class="token punctuation">(</span><span class="token string">'代码操作记录'</span><span class="token punctuation">)</span>
headings <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">'日期'</span><span class="token punctuation">,</span> <span class="token string">'数据1'</span><span class="token punctuation">,</span> <span class="token string">'数据2'</span><span class="token punctuation">]</span>
worksheet1<span class="token punctuation">.</span>write_row<span class="token punctuation">(</span><span class="token string">'A1'</span><span class="token punctuation">,</span> headings<span class="token punctuation">)</span>

data <span class="token operator">=</span> <span class="token punctuation">[</span>
    <span class="token punctuation">[</span><span class="token string">'2022-{i}'</span><span class="token punctuation">.</span><span class="token builtin">format</span><span class="token punctuation">(</span>i<span class="token operator">=</span>i<span class="token punctuation">)</span> <span class="token keyword">for</span> i <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">13</span><span class="token punctuation">)</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span>random<span class="token punctuation">.</span>randint<span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">100</span><span class="token punctuation">)</span> <span class="token keyword">for</span> i <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token number">12</span><span class="token punctuation">)</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span>random<span class="token punctuation">.</span>randint<span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">100</span><span class="token punctuation">)</span> <span class="token keyword">for</span> i <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token number">12</span><span class="token punctuation">)</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
<span class="token punctuation">]</span>
worksheet1<span class="token punctuation">.</span>write_column<span class="token punctuation">(</span><span class="token string">'A2'</span><span class="token punctuation">,</span> data<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
worksheet1<span class="token punctuation">.</span>write_column<span class="token punctuation">(</span><span class="token string">'B2'</span><span class="token punctuation">,</span> data<span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
worksheet1<span class="token punctuation">.</span>write_column<span class="token punctuation">(</span><span class="token string">'C2'</span><span class="token punctuation">,</span> data<span class="token punctuation">[</span><span class="token number">2</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
wb<span class="token punctuation">.</span>close<span class="token punctuation">(</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="新建图表对象" tabindex="-1"><a class="header-anchor" href="#新建图表对象" aria-hidden="true">#</a> 新建图表对象</h2>
<p>数据写好了，但是 Excel 不仅仅只是存放数据的，也可以生成图表。下面我们就学习下如何生成图表。</p>
<p>图表的数据，直接使用<strong>数据1</strong>和<strong>数据2</strong>的内容，并且前半部分，数据的写入就是上面的代码。</p>
<p>数据写入之后，不关闭，然后继续操作，生成一个图表信息。我先把上一部分的代码 copy 在下面：</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code><span class="token keyword">import</span> xlsxwriter<span class="token punctuation">,</span> random  <span class="token comment"># 导入模块</span>

wb <span class="token operator">=</span> xlsxwriter<span class="token punctuation">.</span>Workbook<span class="token punctuation">(</span><span class="token string">'xlsxwriter插入数据和折线图.xlsx'</span><span class="token punctuation">)</span>  <span class="token comment"># 创建新的excel</span>

worksheet1 <span class="token operator">=</span> wb<span class="token punctuation">.</span>add_worksheet<span class="token punctuation">(</span><span class="token string">'代码操作记录'</span><span class="token punctuation">)</span>  <span class="token comment"># 创建新的sheet</span>

headings <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">'日期'</span><span class="token punctuation">,</span> <span class="token string">'数据1'</span><span class="token punctuation">,</span> <span class="token string">'数据2'</span><span class="token punctuation">]</span>  <span class="token comment"># 创建表头</span>

data <span class="token operator">=</span> <span class="token punctuation">[</span>
    <span class="token punctuation">[</span><span class="token string">'2022-1'</span><span class="token punctuation">,</span> <span class="token string">'2022-2'</span><span class="token punctuation">,</span> <span class="token string">'2022-3'</span><span class="token punctuation">,</span> <span class="token string">'2022-4'</span><span class="token punctuation">,</span> <span class="token string">'2022-5'</span><span class="token punctuation">,</span> <span class="token string">'2022-6'</span><span class="token punctuation">,</span> <span class="token string">'2022-7'</span><span class="token punctuation">,</span> <span class="token string">'2022-8'</span><span class="token punctuation">,</span> <span class="token string">'2022-9'</span><span class="token punctuation">,</span> <span class="token string">'2022-10'</span><span class="token punctuation">,</span> <span class="token string">'2022-11'</span><span class="token punctuation">,</span>
     <span class="token string">'2022-12'</span><span class="token punctuation">,</span> <span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span>random<span class="token punctuation">.</span>randint<span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">100</span><span class="token punctuation">)</span> <span class="token keyword">for</span> i <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token number">12</span><span class="token punctuation">)</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span>random<span class="token punctuation">.</span>randint<span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">100</span><span class="token punctuation">)</span> <span class="token keyword">for</span> i <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token number">12</span><span class="token punctuation">)</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
<span class="token punctuation">]</span>

worksheet1<span class="token punctuation">.</span>write_row<span class="token punctuation">(</span><span class="token string">'A1'</span><span class="token punctuation">,</span> headings<span class="token punctuation">)</span>

worksheet1<span class="token punctuation">.</span>write_column<span class="token punctuation">(</span><span class="token string">'A2'</span><span class="token punctuation">,</span> data<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
worksheet1<span class="token punctuation">.</span>write_column<span class="token punctuation">(</span><span class="token string">'B2'</span><span class="token punctuation">,</span> data<span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
worksheet1<span class="token punctuation">.</span>write_column<span class="token punctuation">(</span><span class="token string">'C2'</span><span class="token punctuation">,</span> data<span class="token punctuation">[</span><span class="token number">2</span><span class="token punctuation">]</span><span class="token punctuation">)</span>  <span class="token comment"># 将数据插入到表格中</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>第一部分，折线图表的定义：</strong></p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>chart_col <span class="token operator">=</span> wb<span class="token punctuation">.</span>add_chart<span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token string">'type'</span><span class="token punctuation">:</span> <span class="token string">'line'</span><span class="token punctuation">}</span><span class="token punctuation">)</span>        <span class="token comment">#新建图表格式 line 为折线图</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>有了图表对象，下面就是往里加入数据。</p>
<h2 id="图表数据配置" tabindex="-1"><a class="header-anchor" href="#图表数据配置" aria-hidden="true">#</a> 图表数据配置</h2>
<p>这里的数据有两条，一个是数据1，一个是数据2，所以图表添加数据的代码如下：</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>chart_col<span class="token punctuation">.</span>add_series<span class="token punctuation">(</span>  <span class="token comment"># 给图表设置格式，填充内容</span>
    <span class="token punctuation">{</span>
        <span class="token string">'name'</span><span class="token punctuation">:</span> <span class="token string">'=代码操作记录!$B$1'</span><span class="token punctuation">,</span>
        <span class="token string">'categories'</span><span class="token punctuation">:</span> <span class="token string">'=代码操作记录!$A$2:$A$7'</span><span class="token punctuation">,</span>
        <span class="token string">'values'</span><span class="token punctuation">:</span> <span class="token string">'=代码操作记录!$B$2:$B$7'</span><span class="token punctuation">,</span>
        <span class="token string">'line'</span><span class="token punctuation">:</span> <span class="token punctuation">{</span><span class="token string">'color'</span><span class="token punctuation">:</span> <span class="token string">'blue'</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">)</span>
chart_col<span class="token punctuation">.</span>add_series<span class="token punctuation">(</span>  <span class="token comment"># 给图表设置格式，填充内容</span>
    <span class="token punctuation">{</span>
        <span class="token string">'name'</span><span class="token punctuation">:</span> <span class="token string">'=代码操作记录!$C$1'</span><span class="token punctuation">,</span>
        <span class="token string">'categories'</span><span class="token punctuation">:</span> <span class="token string">'=代码操作记录!$A$2:$A$7'</span><span class="token punctuation">,</span>
        <span class="token string">'values'</span><span class="token punctuation">:</span> <span class="token string">'=代码操作记录!$C$2:$C$7'</span><span class="token punctuation">,</span>
        <span class="token string">'line'</span><span class="token punctuation">:</span> <span class="token punctuation">{</span><span class="token string">'color'</span><span class="token punctuation">:</span> <span class="token string">'green'</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>有两条数据，所以添加了两次。</p>
<p>数据有四项，数据名、具体值对应的横坐标 categories、具体值对应的纵坐标 values、折线颜色，其中取值方式，直接是使用 sheet 的坐标形式，例如 name 是 B1 和 B2，categories 都是 A2-A7，值分别是 B2-B7 和 C2-C7。</p>
<h2 id="完成图表" tabindex="-1"><a class="header-anchor" href="#完成图表" aria-hidden="true">#</a> 完成图表</h2>
<p>数据添加之后，在设置下坐标的相关信息，就是标题、x轴、y轴的名字，以及图表位置和大小，代码如下：</p>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>chart_col<span class="token punctuation">.</span>set_title<span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token string">'name'</span><span class="token punctuation">:</span> <span class="token string">'虚假数据折线图'</span><span class="token punctuation">}</span><span class="token punctuation">)</span>
chart_col<span class="token punctuation">.</span>set_x_axis<span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token string">'name'</span><span class="token punctuation">:</span> <span class="token string">"横坐标"</span><span class="token punctuation">}</span><span class="token punctuation">)</span>
chart_col<span class="token punctuation">.</span>set_y_axis<span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token string">'name'</span><span class="token punctuation">:</span> <span class="token string">'纵坐标'</span><span class="token punctuation">}</span><span class="token punctuation">)</span>  <span class="token comment"># 设置图表表头及坐标轴</span>

worksheet1<span class="token punctuation">.</span>insert_chart<span class="token punctuation">(</span><span class="token string">'D2'</span><span class="token punctuation">,</span> chart_col<span class="token punctuation">,</span> <span class="token punctuation">{</span><span class="token string">'x_offset'</span><span class="token punctuation">:</span> <span class="token number">25</span><span class="token punctuation">,</span> <span class="token string">'y_offset'</span><span class="token punctuation">:</span> <span class="token number">10</span><span class="token punctuation">}</span><span class="token punctuation">)</span>  <span class="token comment"># 放置图表位置</span>
<span class="token comment"># worksheet1.insert_chart('D2', chart_col)  # 放置图表位置</span>
wb<span class="token punctuation">.</span>close<span class="token punctuation">(</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>图表的位置和大小，是根据左上角的起始表格和 x 和 y 的偏移计算的。</p>
<p>代码中是从 D2 做左上角起始，然后 x 和 y 分别偏移 25 和 10 个单位，得到了图片的最终大小。最后关闭 wb。</p>
<p>下面是最后的 Excel 文件样式：</p>
<p><img src="@source/column/pyauto/auto_base11.assets/image-20220717201003183.png" alt="image-20220717201003183" loading="lazy"></p>
<p>以上就是 xlsxwriter 的使用示例，有图的加入，比较有趣。但是 xlsxwriter 只能创建新的文件，不能追加和读取。</p>
<h2 id="完整代码" tabindex="-1"><a class="header-anchor" href="#完整代码" aria-hidden="true">#</a> 完整代码</h2>
<div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code><span class="token keyword">import</span> xlsxwriter
<span class="token keyword">import</span> random  <span class="token comment"># 导入模块</span>

wb <span class="token operator">=</span> xlsxwriter<span class="token punctuation">.</span>Workbook<span class="token punctuation">(</span><span class="token string">'xlsxwriter插入数据.xlsx'</span><span class="token punctuation">)</span>
worksheet1 <span class="token operator">=</span> wb<span class="token punctuation">.</span>add_worksheet<span class="token punctuation">(</span><span class="token string">'代码操作记录'</span><span class="token punctuation">)</span>
headings <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">'日期'</span><span class="token punctuation">,</span> <span class="token string">'数据1'</span><span class="token punctuation">,</span> <span class="token string">'数据2'</span><span class="token punctuation">]</span>
worksheet1<span class="token punctuation">.</span>write_row<span class="token punctuation">(</span><span class="token string">'A1'</span><span class="token punctuation">,</span> headings<span class="token punctuation">)</span>

data <span class="token operator">=</span> <span class="token punctuation">[</span>
    <span class="token punctuation">[</span><span class="token string">'2022-{i}'</span><span class="token punctuation">.</span><span class="token builtin">format</span><span class="token punctuation">(</span>i<span class="token operator">=</span>i<span class="token punctuation">)</span> <span class="token keyword">for</span> i <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">13</span><span class="token punctuation">)</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span>random<span class="token punctuation">.</span>randint<span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">100</span><span class="token punctuation">)</span> <span class="token keyword">for</span> i <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token number">12</span><span class="token punctuation">)</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
    <span class="token punctuation">[</span>random<span class="token punctuation">.</span>randint<span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">100</span><span class="token punctuation">)</span> <span class="token keyword">for</span> i <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token number">12</span><span class="token punctuation">)</span><span class="token punctuation">]</span><span class="token punctuation">,</span>
<span class="token punctuation">]</span>
worksheet1<span class="token punctuation">.</span>write_column<span class="token punctuation">(</span><span class="token string">'A2'</span><span class="token punctuation">,</span> data<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
worksheet1<span class="token punctuation">.</span>write_column<span class="token punctuation">(</span><span class="token string">'B2'</span><span class="token punctuation">,</span> data<span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
worksheet1<span class="token punctuation">.</span>write_column<span class="token punctuation">(</span><span class="token string">'C2'</span><span class="token punctuation">,</span> data<span class="token punctuation">[</span><span class="token number">2</span><span class="token punctuation">]</span><span class="token punctuation">)</span>

<span class="token comment"># 开始画图表</span>
chart_col <span class="token operator">=</span> wb<span class="token punctuation">.</span>add_chart<span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token string">'type'</span><span class="token punctuation">:</span> <span class="token string">'line'</span><span class="token punctuation">}</span><span class="token punctuation">)</span>
chart_col<span class="token punctuation">.</span>add_series<span class="token punctuation">(</span>
    <span class="token punctuation">{</span>
        <span class="token string">'name'</span><span class="token punctuation">:</span> <span class="token string">'=代码操作记录!$B$1'</span><span class="token punctuation">,</span>
        <span class="token string">'categories'</span><span class="token punctuation">:</span> <span class="token string">'=代码操作记录!$A$2:$A$7'</span><span class="token punctuation">,</span>
        <span class="token string">'values'</span><span class="token punctuation">:</span>   <span class="token string">'=代码操作记录!$B$2:$B$7'</span><span class="token punctuation">,</span>
        <span class="token string">'line'</span><span class="token punctuation">:</span> <span class="token punctuation">{</span><span class="token string">'color'</span><span class="token punctuation">:</span> <span class="token string">'blue'</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">)</span>
chart_col<span class="token punctuation">.</span>add_series<span class="token punctuation">(</span>
    <span class="token punctuation">{</span>
        <span class="token string">'name'</span><span class="token punctuation">:</span> <span class="token string">'=代码操作记录!$C$1'</span><span class="token punctuation">,</span>
        <span class="token string">'categories'</span><span class="token punctuation">:</span> <span class="token string">'=代码操作记录!$A$2:$A$7'</span><span class="token punctuation">,</span>
        <span class="token string">'values'</span><span class="token punctuation">:</span>   <span class="token string">'=代码操作记录!$C$2:$C$7'</span><span class="token punctuation">,</span>
        <span class="token string">'line'</span><span class="token punctuation">:</span> <span class="token punctuation">{</span><span class="token string">'color'</span><span class="token punctuation">:</span> <span class="token string">'green'</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">)</span>
chart_col<span class="token punctuation">.</span>set_title<span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token string">'name'</span><span class="token punctuation">:</span> <span class="token string">'虚假数据折线图'</span><span class="token punctuation">}</span><span class="token punctuation">)</span>
chart_col<span class="token punctuation">.</span>set_x_axis<span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token string">'name'</span><span class="token punctuation">:</span> <span class="token string">"横坐标"</span><span class="token punctuation">}</span><span class="token punctuation">)</span>
chart_col<span class="token punctuation">.</span>set_y_axis<span class="token punctuation">(</span><span class="token punctuation">{</span><span class="token string">'name'</span><span class="token punctuation">:</span> <span class="token string">'纵坐标'</span><span class="token punctuation">}</span><span class="token punctuation">)</span>  <span class="token comment"># 设置图表表头及坐标轴</span>

worksheet1<span class="token punctuation">.</span>insert_chart<span class="token punctuation">(</span>
    <span class="token string">'D2'</span><span class="token punctuation">,</span> chart_col<span class="token punctuation">,</span> <span class="token punctuation">{</span><span class="token string">'x_offset'</span><span class="token punctuation">:</span> <span class="token number">25</span><span class="token punctuation">,</span> <span class="token string">'y_offset'</span><span class="token punctuation">:</span> <span class="token number">10</span><span class="token punctuation">}</span><span class="token punctuation">)</span>  <span class="token comment"># 放置图表位置</span>

wb<span class="token punctuation">.</span>close<span class="token punctuation">(</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>欢迎关注我公众号：AI悦创，有更多更好玩的等你发现！</p>
<details class="custom-container details"><summary>公众号：AI悦创【二维码】</summary>
<p><img src="/gzh.jpg" alt="" loading="lazy"></p>
</details>
<div class="custom-container info">
<p class="custom-container-title">AI悦创·编程一对一</p>
<p>AI悦创·推出辅导班啦，包括「Python 语言辅导班、C++ 辅导班、java 辅导班、算法/数据结构辅导班、少儿编程、pygame 游戏开发」，全部都是一对一教学：一对一辅导 + 一对一答疑 + 布置作业 + 项目实践等。当然，还有线下线上摄影课程、Photoshop、Premiere 一对一教学、QQ、微信在线，随时响应！微信：Jiabcdefh</p>
<p>C++ 信息奥赛题解，长期更新！长期招收一对一中小学信息奥赛集训，莆田、厦门地区有机会线下上门，其他地区线上。微信：Jiabcdefh</p>
<p>方法一：<a href="http://wpa.qq.com/msgrd?v=3&amp;uin=1432803776&amp;site=qq&amp;menu=yes" target="_blank" rel="noopener noreferrer">QQ<ExternalLinkIcon/></a></p>
<p>方法二：微信：Jiabcdefh</p>
</div>
<p><img src="/zsxq.jpg" alt="" loading="lazy"></p>
</div></template>


